### ISSUE TITLE
Plot does not show

### ISSUE THREAD

**Issue by griff10000** [JSSpaulding/rgeoprofile#1]
Hi, I have run the examples in package rgeoprofile which create 'g_map' but it doesn't display.
I am using: 
    R version 3.5.3 (2019-03-11)
    RStudio Version 1.2.5042
    running under Windows 10 on a standard PC.

Do I need to load a separate library to produce a plot?

**Comment by JSSpaulding** [comment]
The package does require 'leaflet', 'sp', and 'raster' to plot the resultant geographic profile. I have just tested the example below on R 3.6.3 without issue. It will install and load all necessary packages for you. Please let me know if this is not working or if you are still having difficulties.

`
pkgs <- c("rgeoprofile", "leaflet", "sp", "raster", "pals")
install.packages(pkgs) #installs packages listed in pkgs
lapply(pkgs, library, character.only = TRUE) #loads required packages in pkgs

data("desalvo")

test <- cgt_profile(desalvo$lat, desalvo$lon)
g_map = sp::SpatialPixelsDataFrame(points = test[c("lons", "lats")], data = test)
g_map <- raster::raster(g_map)
# Assign a Coordinate Reference System for the Raster
raster::crs(g_map) <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
# Define a Parula Color Pallete for Resultant Jeopardy Surface
pal <- colorNumeric(pals::parula(200), raster::values(g_map),
                    na.color = "transparent")
leaflet() %>%
  addTiles() %>%
  addProviderTiles('Esri.WorldTopoMap', group = 'Topo') %>%
  addAwesomeMarkers(lng = -71.07357, lat = 42.41322, icon =
                      awesomeIcons(icon = 'home', markerColor = 'green'), popup = 'Residence') %>%
  addRasterImage(g_map, colors = pal, opacity = 0.6) %>%
  addLegend(pal = pal, values = raster::values(g_map), title = 'Score') %>%
  addCircleMarkers(lng = desalvo$lon, lat = desalvo$lat, radius = 4, opacity = 1,
                   fill = 'black', stroke = TRUE, fillOpacity = 0.75, weight = 2,
                   fillColor = "red")
`

**Comment by griff10000** [comment]
Hi Jamie,

 

Thank you for your reply.

 

I ran your code, but still with no plot showing.

 

However, on running:

 

> require(grDevices)

> plot(g_map)

 

I obtained the plot

 

Many thanks,

 

Regards,

 

Graham W Griffiths
